FROM golang:alpine as builder
ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64 \
	GOPROXY="https://goproxy.cn,direct"
WORKDIR /usr/app/
COPY . .
RUN go build -o docker-server ./server/docker-server

FROM  alpine:latest
ENV  TIME_ZONE  Asia/Shanghai
WORKDIR  /usr/app/
COPY  --from=builder /usr/app/docker-server  .
CMD  ["/usr/app/docker-server"]
