apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-server
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: docker-server
  template:
    metadata:
      labels:
        app: docker-server
    spec:
      containers:
        - env:
            - name: httpAddr
              value: "10.2.76.169"
            - name: serverAddr
              value: "10.2.76.169"
          image: xxx/xx/docker-server:v3
          imagePullPolicy: Always
          name: docker-server
          ports:
            - containerPort: 30000
              name: server
            - containerPort: 8080
              name: http
          resources:
            limits:
              cpu: "30m"
              memory: 50Mi
            requests:
              cpu: 10m
              memory: 10Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/localtime
              name: host-time
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: docker-server-svc
spec:
  ports:
    - port: 30000
      protocol: TCP
      targetPort: 30000
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: docker-server
  sessionAffinity: None
  type: ClusterIP
